language: cpp
before_script:
- sudo apt-get install graphviz
- sudo apt-get install doxygen
script:
- cd Homework5
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen $TRAVIS_BUILD_DIR/Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -T homework5-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uVladislavTyurin:$BINTRAY_API_KEY "https://api.bintray.com/content/vladislavtyurin/otus-cpp/homework5/$TRAVIS_BUILD_NUMBER/homework5-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  
  - provider: pages
    skip-cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
