language: cpp
#before_script:
#- sudo apt-get install libboost-test-dev -y
#- cd Homework2
script:
- cd Homework2
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uVladislavTyurin:$BINTRAY_API_KEY "https://api.bintray.com/content/vladislavtyurin/otus-cpp/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
