language: cpp
before_script:
- sudo apt-get install doxygen
script:
- cd Homework4
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package
#- doxygen -g $TRAVIS_BUILD_DIR/Doxyfile
- doxygen $TRAVIS_BUILD_DIR/Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep_history: false
  on:
    branch: master
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uVladislavTyurin:$BINTRAY_API_KEY "https://api.bintray.com/content/vladislavtyurin/otus-cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
